### ISSUE TITLE
http mocks regardless of domain

### ISSUE THREAD

**Issue by justman00** [jarcoal/httpmock#132]
Hey,

It looks like httpmock, mocks the HTTP transporter regardless of the domain that is being called.

```go
func Test_mockHTTP(t *testing.T) {
	httpmock.Activate()

	// I only want to mock the https://some-domain.com
	httpmock.RegisterResponder(http.MethodGet, "https://some-domain.com", httpmock.NewStringResponder(http.StatusOK, "hello world"))

	client := http.Client{}

	// The request should get intercepted
	_, err := client.Get("https://some-domain.com")
	require.NoError(t, err)

	// The request should NOT get intercepted, but it does and fails with Get "https://sumup.com": no responder found
	_, err = client.Get("https://gitlab.com")
	require.NoError(t, err)
}
```

If this is not by design, I am happy to submit a PR

**Comment by maxatome** [comment]
Hello, yes httpmock replaces the `net/http.Client` instance by its own. So for each instance, all requests are diverted, it is by design. You can play with [`RegisterNoResponder`](https://pkg.go.dev/github.com/jarcoal/httpmock#RegisterNoResponder) to handle such cases where for a single client you want only mock one domain / URL:
```golang
httpmock.RegisterNoResponder(httpmock.InitialTransport.RoundTrip)
```

**Comment by justman00** [comment]
okay, thank you for the quick answer 🙏
