### ISSUE TITLE
BUG: TestMockTransportRespectsTimeout does not reflect why fails

### ISSUE THREAD

**Issue by mckaygerhard** [jarcoal/httpmock#31]
i got a faild in arm64 setup:

=== RUN   TestMockTransportRespectsTimeout
--- FAIL: TestMockTransportRespectsTimeout (0.00s)

bug i cannot make a trace or find why, my skills in go are limited and the package does not provide any kind for

**Comment by dlebech** [comment]
@mckaygerhard your test probably [fails here](https://github.com/jarcoal/httpmock/blob/cf52904a3cf0f78f199ecade6a6df8e245d5b25a/transport_test.go#L295-L298). It expects a timeout error from the http client and if does not get that, it fails the test. Since the timeout is only 1-2 ms, it could be that the arm architecture does not have that kind of granularity.

You could try to change [this line](https://github.com/jarcoal/httpmock/blob/cf52904a3cf0f78f199ecade6a6df8e245d5b25a/transport_test.go#L279) to something a bit more extreme like:
`timeout := time.Second`

**Comment by mckaygerhard** [comment]
i tried and seems works in a older arm setup in debian squeeze, but sorry but i cannot make sure if this are the definitive solution due the right build environment are not more accedible to me... i'll close it when other response can confirm me the solution or a better borkaround are find

**Comment by maxatome** [comment]
@mckaygerhard do you have any news about this problem?

**Comment by maxatome** [comment]
@mckaygerhard  since #70 Sleep() time is now 100 × client timeout, so it should solve your problem. Please reopen if the problem persist.
